[phases.setup]
nixPkgs = ["maven", "jdk17"]

[phases.build]
cmds = ["./mvnw clean package -DskipTests"]

[phases.start]
cmd = "java -Dserver.port=$PORT $JAVA_OPTS -jar target/library-0.0.1-SNAPSHOT.jar"
