# Railway Deployment Configuration
version = "3"

[build]
builder = "nixpacks"

[deploy]
startCommand = "java -Dserver.port=$PORT -jar target/library-0.0.1-SNAPSHOT.jar"

[env]
SPRING_PROFILES_ACTIVE = "prod"
MONGODB_URI = "${{MONGODB_URI}}"
PORT = "${{PORT}}"
CORS_ORIGINS = "${{CORS_ORIGINS}}"
ADMIN_USERNAME = "${{ADMIN_USERNAME}}"
ADMIN_PASSWORD = "${{ADMIN_PASSWORD}}"
EMAIL_USERNAME = "${{EMAIL_USERNAME}}"
EMAIL_PASSWORD = "${{EMAIL_PASSWORD}}"